# Generated by Django 4.2.3 on 2023-09-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_brand_product_category_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Default Category', max_length=200, null=True),
        ),
    ]
