# Generated by Django 4.2.3 on 2023-09-22 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_digital'),
        ('user', '0002_remove_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(default='kala', on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='store.shippingaddress'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(default='knr', on_delete=django.db.models.deletion.CASCADE, related_name='user_city', to='store.shippingaddress'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(default='krla', on_delete=django.db.models.deletion.CASCADE, related_name='user_state', to='store.shippingaddress'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.ForeignKey(default='7865', on_delete=django.db.models.deletion.CASCADE, related_name='user_zipcode', to='store.shippingaddress'),
        ),
    ]
