# Generated by Django 4.2.3 on 2023-09-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_address_profile_city_profile_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
    ]
